config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :art_pieces, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: :destroy

  resources :bookings, only: [:edit, :show] do
    patch "accept", to: "bookings#accept"
    patch "decline", to: "bookings#declined"
  end
  resources :dashboards, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art_piece.rb
class ArtPiece < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
  has_one_attached :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :art_piece
  belongs_to :user
  validates :start_time, :end_time, presence: true
  validates :status, acceptance: {accept: ['validate', 'decline', 'waiting']}
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :art_piece
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :art_pieces
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
  
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
  
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/art_pieces_controller.rb
class ArtPiecesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR category ILIKE :query OR artist ILIKE :query"
      @art_pieces = policy_scope(ArtPiece).where(sql_query, query: "%#{params[:query]}%")
    else
      @art_pieces = policy_scope(ArtPiece).order(created_at: :desc)
    end
  end

  def show
    @art_piece = ArtPiece.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    authorize @art_piece
  end

  def new
    @art_piece = ArtPiece.new
    authorize @art_piece
  end

  def create
    @art_piece = ArtPiece.new(whitelist)
    authorize @art_piece
    @art_piece.user = current_user
    @art_piece.save
    redirect_to art_pieces_path(current_user)
  end

  private

  def whitelist
    params.require(:art_piece).permit(:title, :artist, :description, :category, :painting_technic, :size, :unit_price, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @art_piece = ArtPiece.find(params[:art_piece_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @art_piece = ArtPiece.find(params[:art_piece_id])
    @booking = Booking.new(whitelist)
    @booking.status = "waiting"
    authorize @booking
    @booking.art_piece = @art_piece
    @booking.user = current_user
    days = @booking.end_time - @booking.start_time + 1
    @booking.price = days * @art_piece.unit_price
    if @booking.save
      sleep 3
      redirect_to dashboards_path(current_user)
    else
      redirect_to art_piece_path(@art_piece)
    end
  end

  def edit
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.update(status:'validate')
    authorize @booking
    # redirect_to dashboards_path(current_user)
  end

  def declined
    @booking = Booking.find(params[:booking_id])
    @booking.update(status:'decline')
    authorize @booking
    # redirect_to dashboards_path(current_user)
  end

  def show
  end

  private

  def whitelist
    params.require(:booking).permit(:start_time, :end_time)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @dashboards = policy_scope(Dashboard)
    @bookings = current_user.bookings
    @pending_bookings = []
    current_user.art_pieces.each do |art_piece|
      art_piece.bookings.each do |booking|
        @pending_bookings << booking
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :find_review, only: [:destroy]

  def new
    @art_piece = ArtPiece.find(params[:art_piece_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.art_piece = ArtPiece.find(params[:art_piece_id])
    authorize @review
    @review.user = current_user
    if @review.save
      redirect_to art_piece_path(@review.art_piece)
    else
      redirect_to art_piece_path(@art_piece)
    end
  end

  def destroy
    @art_piece = @review.art_piece
    @review.destroy
    redirect_to art_piece_path(@art_piece)
  end

  private

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/art_pieces/index.html.erb
<div class="index-container" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "art_gallery_2.jpg", height: 100 %>'); background-position: center">
  <div class="art-pieces-container">
    <h1 class="mt-4">Discover our Art Pieces</h1>
    <div class="mt-5">
      <%= render "shared/search" %>
    </div>
    <div class="cards mb-4">
      <% @art_pieces.each do |art_piece| %>
        <div class="card-art-pieces">
          <% if art_piece.picture.nil? %>
            <%= cl_image_tag art_piece.photo.key, height: 250, width: 276, crop: :fill %>
          <% else %>
            <img src="<%= art_piece.picture %>">
          <% end %>
          <div class="card-art-pieces-infos">
            <div class="card-art-pieces-infos-details">
              <h2><%= art_piece.title %> <span>• <%= art_piece.artist %></span></h2>
            </div>
            <div class="card-art-pieces-booking">
              <%= link_to 'See details', art_piece_path(art_piece) %>
              <h2 class="card-art-pieces-pricing"><%= art_piece.unit_price %>€</h2>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/art_pieces/new.html.erb
<div class="container-new" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "art_gallery_2.jpg", crop: :fill %>'); background-position: center">
  <div class="container">
    <h2 class="mb-4">Rent out your art piece !</h2>
    <%= simple_form_for @art_piece do |f| %>
      <%= f.input :title, as: :string, required: true %>
      <%= f.input :artist, as: :string, required: true %>
      <%= f.input :description, as: :string, required: true %>
      <%= f.input :category, as: :string, required: true %>
      <%= f.input :painting_technic, as: :string, required: true %>
      <%= f.input :size, as: :string, required: true %>
      <%= f.input :unit_price, as: :integer, required: true %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, "Publish", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/art_pieces/show.html.erb
<div class="container-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "art_gallery_2.jpg", crop: :fill %>'); background-position: center">
  <div class="show-container">
    <div class="art-piece-container mt-4 mb-4">
      <h2><%= @art_piece.title %><h2>
      <h3><%= @art_piece.artist %> • <span class="size"><%= @art_piece.size %></span></h3>
      <% if @art_piece.picture.nil? %>
        <%= cl_image_tag @art_piece.photo.key, height: 250, width: 276, crop: :fill %>
      <% else %>
        <img src="<%= @art_piece.picture %>">
      <% end %>
      <div class="art-piece-infos">
        <div>
          <div class="caracteristics mt-4">
            <i class="fas fa-quote-left mr-3"></i>
            <div class="text">
              <p><strong>Description</strong></p>
              <p><%= @art_piece.description %></p>
            </div>
          </div>
          <div class="caracteristics mt-3">
            <i class="fas fa-sitemap mr-3"></i>
            <div class="text">
              <p><strong>Category</strong></p>
              <p><%= @art_piece.category %></p>
            </div>
          </div>
          <div class="caracteristics mt-3">
            <i class="fas fa-paint-brush mr-3"></i>
            <div class="text">
              <p><strong>Painting Technique</strong></p>
              <p><%= @art_piece.painting_technic %></p>
            </div>
          </div>
          <h3 class="art-piece-pricing" data-price="<%= @art_piece.unit_price %>"><%= @art_piece.unit_price %>€/day</h3>
        </div>
      </div>
    </div>
    <div class="booking-form mt-4">

      <div class="form-wrapper reservation-form">
        <h2 class="mb-4">Book this art piece</h2>
        <%= simple_form_for [ @art_piece, @booking ] do |f| %>
          <%= f.input :start_time, as: :string, required: false, input_html: {id: "datepicker1"} %>
          <%= f.input :end_time, as: :string, required: false, input_html: {id: "datepicker2"} %>
          <%= f.button :submit, "Book", class: "btn btn-primary", data: { toggle: "modal", target: "#exampleModal" } %>
        <% end %>
        <div class="price mt-3"></div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Booking Confirmed !</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="review-form">
        <h3><%= pluralize @art_piece.reviews.size, "review" %></h3>
        <div id="reviews">
          <% if @art_piece.reviews.blank? %>
            <p><em> Be the first to leave a review </em></p>
          <% else %>
            <% @art_piece.reviews.each do |review| %>
            <p><%= review.content %></p>
          <% end %>
        <% end %>
        </div>
        <div class="form-wrapper">
          <%= simple_form_for [ @art_piece, @review ] do |f| %>
          <%= f.input :rating, input_html: { style: 'width: 50%' } %>
          <%= f.input :content, placeholder: 'Leave your review', label: false, input_html: { style: 'width: 300px' } %>
          <%= f.button :submit, "Comment", class: "btn btn-outline-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/dashboards/index.html.erb
<div class="dashboard" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "art_gallery_3.jpg", crop: :fill %>')">

  <div class="dashboard-container">

    <div class="dashboard-tab">
      <ul class="list-inline tabs-underlined">
        <li>
          <a href="" class="tab-underlined active" data-order="0">My Bookings</a>
        </li>
        <li>
          <a href="" class="tab-underlined" data-order="1">My Collection</a>
        </li>
      </ul>
    </div>

    <div class="contents">
      <div class="content bookings">
        <div class="container mb-5 message">
          <div class="d-flex justify-content-between my-4">
            <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any paintings yet!" if @bookings.empty? %></em></small></span>
          </div>
        </div>
        <div class="content-infos">
          <% @bookings.each do |booking| %>
            <ul class="dashboard-card">
              <div class="card-product">
                <div class="card-image">
                  <% if booking.art_piece.picture.nil? %>
                    <%= cl_image_tag booking.art_piece.photo.key, height: 178, width: 120, crop: :fill %>
                  <% else %>
                    <img src="<%= booking.art_piece.picture %>">
                  <% end %>
                </div>
                <div class="card-title">
                  <h2><%= link_to booking.art_piece.title, art_piece_path(booking.art_piece.id) %></h2>
                </div>
                <div class="card-dates">
                  <p><%= booking.start_time.strftime('%a, %d, %b') %> - <%= booking.end_time.strftime('%a, %d, %b') %></p>
                </div>
                <div class="card-price">
                  <p><%= booking.price %> €</p>
                </div>
                <div class="card-statut">
                  <p><%= booking.status %></p>
                </div>
              </ul>
          <% end %>
        </div>
        <div class="btn btn-group">
          <%= link_to 'Book another painting', art_pieces_path, class: "btn btn-outline-dark" %>
        </div>
      </div>

      <div class="content collection inactive">
        <div class="container mb-5 message">
          <div class="d-flex justify-content-between my-4">
            <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't posted any paintings yet!" if @bookings.empty? %></em></small></span>
          </div>
        </div>
        <div class="content-infos">
          <% @pending_bookings.each do |booking| %>
            <ul class="dashboard-card">
              <div class="card-product">
                <div class="card-image">
                  <% if booking.art_piece.picture.nil? %>
                    <%= cl_image_tag booking.art_piece.photo.key, height: 178, width: 120, crop: :fill %>
                  <% else %>
                    <img src="<%= booking.art_piece.picture %>">
                  <% end %>
                </div>
                <div class="card-title">
                  <h2><%= link_to booking.art_piece.title, art_piece_path(booking.art_piece.id) %></h2>
                </div>
                <div class="card-dates">
                  <p><%= booking.start_time.strftime('%a, %d, %b') %> - <%= booking.end_time.strftime('%a, %d, %b') %></p>
                </div>
                <div class="card-price">
                  <p><%= booking.price %> €</p>
                </div>
                <div class="card-statut">
                  <% if booking.status == "waiting"%>
                    <div class="btn btn-group accept-decline" data-status="accept">
                      <%= link_to 'Accept', booking_accept_path(booking), remote: true, method: :patch, class: "btn btn-outline-success" %>
                    </div>
                    <div class="btn btn-group accept-decline" data-status="decline">
                      <%= link_to 'Decline', booking_decline_path(booking), remote: true, method: :patch, class: "btn btn-outline-danger" %>
                    </div>
                  <% elsif booking.status == "validate" %>
                    <div class="btn btn-outline-success accept-decline">
                      <p>Booking accepté</p>
                    </div>
                  <% elsif booking.status == "decline" %>
                    <div class="btn btn-outline-danger accept-decline">
                      <p>Booking refusé</p>
                    </div>
                  <%end%>
                </div>
              </div>
            </ul>
          <% end %>
        </div>
        <div class="btn btn-group">
          <%= link_to 'Post another painting', new_art_piece_path, class: "btn btn-outline-dark" %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arteo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="carousel-slides" class="carousel" data-ride="carousel">
  <div class="carousel-text">
    <p>
      <span id="carousel-typed-text"></span>
    </p>
  </div>
  <%= render "shared/search" %>

  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="<%= image_path "art_gallery_1.jpg" %>" class="d-block w-100" alt="art-gallery">
    </div>
    <div class="carousel-item">
      <img src="<%= image_path "art_gallery_2.jpg" %>" class="d-block w-100" alt="art-gallery">
    </div>
    <div class="carousel-item">
      <img src="<%= image_path "art_gallery_3.jpg" %>" class="d-block w-100" alt="art-gallery">
    </div>
  </div>
</div>

<div>
  <h2 class="popular">Have a look at our most popular paintings !</h2>
  <div class="cards ml-4">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1532347939055-0d93107d087e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=704&q=80)">
     <%= link_to "Abstract", art_pieces_path({query:"Abstract"}), class: "home-link" %>
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://maggiesfrenchartblog.weebly.com/uploads/9/6/4/6/9646305/2589888.jpg?617)">
    <%= link_to "Classicism", art_pieces_path({query:"Classicism"}), class: "home-link" %>
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://museefabre.montpellier3m.fr/var/storage/images/media/images/expositions/2020_le_canada_et_l_impressionnisme_-_nouveau_horizons/helen_mcnicoll_septembre_ensoleille_collection_pierre_lassonde/115647-1-fre-FR/HELEN_MCNICOLL_Septembre_ensoleille_Collection_Pierre_Lassonde.jpg)">
    <%= link_to "Impressionnistic", art_pieces_path({query:"Impressionnistic"}), class: "home-link" %>
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1571115764595-644a1f56a55c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=380&q=80)">
     <%= link_to "Street Art", art_pieces_path({query:"Street Art"}), class: "home-link" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <h1>arteo</h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <div class="center-nav-bar">
          <li class="nav-item active">
            <%= link_to "Book a new painting", art_pieces_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My dashboard", dashboards_path, class: "nav-link" %>
        </li>
          </li>
          <li class="nav-item dropdown">
            <div class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%=current_user.first_name.first.capitalize%><%=current_user.last_name.first.capitalize%>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </div>
          </li>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to "Book paintings", art_pieces_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "I own a painting", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="form-group">
  <%= form_tag art_pieces_path, class: "d-flex pb-5", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search by title, artist or category"
      %>
    <%= button_tag(type: "submit", class: "btn btn-default") do %>
       <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>